//! CSS 属性名常量与枚举
//!
//! 用于替换分散在各文件中的字符串字面量，提供编译期检查。

/// CSS 属性标识符 — 整数比较，O(1) 无字符串开销
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PropertyId {
    // 盒模型
    Width,
    Height,
    MinWidth,
    MaxWidth,
    MinHeight,
    MaxHeight,
    Margin,
    MarginTop,
    MarginRight,
    MarginBottom,
    MarginLeft,
    Padding,
    PaddingTop,
    PaddingRight,
    PaddingBottom,
    PaddingLeft,
    Border,
    BorderTop,
    BorderRight,
    BorderBottom,
    BorderLeft,
    BorderRadius,
    // 布局
    Display,
    Position,
    Overflow,
    OverflowX,
    OverflowY,
    Float,
    Clear,
    BoxSizing,
    AspectRatio,
    // 排版
    Color,
    FontSize,
    FontFamily,
    FontWeight,
    FontStyle,
    TextAlign,
    TextDecoration,
    WhiteSpace,
    LineHeight,
    // 视觉
    Background,
    BackgroundColor,
    Opacity,
    BoxShadow,
    // Flexbox
    FlexDirection,
    FlexWrap,
    JustifyContent,
    AlignItems,
    AlignContent,
    FlexGrow,
    FlexShrink,
    FlexBasis,
    AlignSelf,
    Order,
    Flex,
    Gap,
    // Grid
    GridTemplateColumns,
    GridTemplateRows,
    GridColumn,
    GridRow,
    // 表格
    Colspan,
    Rowspan,
    // 定位
    Top,
    Right,
    Bottom,
    Left,
    // 其他
    Transform,
    Transition,
    Animation,
    Visibility,
    ZIndex,
}

impl std::fmt::Display for PropertyId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

impl PropertyId {
    /// 字符串 → PropertyId
    pub fn from_str(s: &str) -> Option<Self> {
        Some(match s {
            "width" => Self::Width,
            "height" => Self::Height,
            "min-width" => Self::MinWidth,
            "max-width" => Self::MaxWidth,
            "min-height" => Self::MinHeight,
            "max-height" => Self::MaxHeight,
            "margin" => Self::Margin,
            "margin-top" => Self::MarginTop,
            "margin-right" => Self::MarginRight,
            "margin-bottom" => Self::MarginBottom,
            "margin-left" => Self::MarginLeft,
            "padding" => Self::Padding,
            "padding-top" => Self::PaddingTop,
            "padding-right" => Self::PaddingRight,
            "padding-bottom" => Self::PaddingBottom,
            "padding-left" => Self::PaddingLeft,
            "border" => Self::Border,
            "border-top" => Self::BorderTop,
            "border-right" => Self::BorderRight,
            "border-bottom" => Self::BorderBottom,
            "border-left" => Self::BorderLeft,
            "border-radius" => Self::BorderRadius,
            "display" => Self::Display,
            "position" => Self::Position,
            "overflow" => Self::Overflow,
            "overflow-x" => Self::OverflowX,
            "overflow-y" => Self::OverflowY,
            "float" => Self::Float,
            "clear" => Self::Clear,
            "box-sizing" => Self::BoxSizing,
            "aspect-ratio" => Self::AspectRatio,
            "color" => Self::Color,
            "font-size" => Self::FontSize,
            "font-family" => Self::FontFamily,
            "font-weight" => Self::FontWeight,
            "font-style" => Self::FontStyle,
            "text-align" => Self::TextAlign,
            "text-decoration" => Self::TextDecoration,
            "white-space" => Self::WhiteSpace,
            "line-height" => Self::LineHeight,
            "background" => Self::Background,
            "background-color" => Self::BackgroundColor,
            "opacity" => Self::Opacity,
            "box-shadow" => Self::BoxShadow,
            "flex-direction" => Self::FlexDirection,
            "flex-wrap" => Self::FlexWrap,
            "justify-content" => Self::JustifyContent,
            "align-items" => Self::AlignItems,
            "align-content" => Self::AlignContent,
            "flex-grow" => Self::FlexGrow,
            "flex-shrink" => Self::FlexShrink,
            "flex-basis" => Self::FlexBasis,
            "align-self" => Self::AlignSelf,
            "order" => Self::Order,
            "flex" => Self::Flex,
            "gap" => Self::Gap,
            "grid-template-columns" => Self::GridTemplateColumns,
            "grid-template-rows" => Self::GridTemplateRows,
            "grid-column" => Self::GridColumn,
            "grid-row" => Self::GridRow,
            "colspan" => Self::Colspan,
            "rowspan" => Self::Rowspan,
            "top" => Self::Top,
            "right" => Self::Right,
            "bottom" => Self::Bottom,
            "left" => Self::Left,
            "transform" => Self::Transform,
            "transition" => Self::Transition,
            "animation" => Self::Animation,
            "visibility" => Self::Visibility,
            "z-index" => Self::ZIndex,
            _ => return None,
        })
    }

    /// PropertyId → CSS 规范名称
    pub fn name(self) -> &'static str {
        match self {
            Self::Width => "width",
            Self::Height => "height",
            Self::MinWidth => "min-width",
            Self::MaxWidth => "max-width",
            Self::MinHeight => "min-height",
            Self::MaxHeight => "max-height",
            Self::Margin => "margin",
            Self::MarginTop => "margin-top",
            Self::MarginRight => "margin-right",
            Self::MarginBottom => "margin-bottom",
            Self::MarginLeft => "margin-left",
            Self::Padding => "padding",
            Self::PaddingTop => "padding-top",
            Self::PaddingRight => "padding-right",
            Self::PaddingBottom => "padding-bottom",
            Self::PaddingLeft => "padding-left",
            Self::Border => "border",
            Self::BorderTop => "border-top",
            Self::BorderRight => "border-right",
            Self::BorderBottom => "border-bottom",
            Self::BorderLeft => "border-left",
            Self::BorderRadius => "border-radius",
            Self::Display => "display",
            Self::Position => "position",
            Self::Overflow => "overflow",
            Self::OverflowX => "overflow-x",
            Self::OverflowY => "overflow-y",
            Self::Float => "float",
            Self::Clear => "clear",
            Self::BoxSizing => "box-sizing",
            Self::AspectRatio => "aspect-ratio",
            Self::Color => "color",
            Self::FontSize => "font-size",
            Self::FontFamily => "font-family",
            Self::FontWeight => "font-weight",
            Self::FontStyle => "font-style",
            Self::TextAlign => "text-align",
            Self::TextDecoration => "text-decoration",
            Self::WhiteSpace => "white-space",
            Self::LineHeight => "line-height",
            Self::Background => "background",
            Self::BackgroundColor => "background-color",
            Self::Opacity => "opacity",
            Self::BoxShadow => "box-shadow",
            Self::FlexDirection => "flex-direction",
            Self::FlexWrap => "flex-wrap",
            Self::JustifyContent => "justify-content",
            Self::AlignItems => "align-items",
            Self::AlignContent => "align-content",
            Self::FlexGrow => "flex-grow",
            Self::FlexShrink => "flex-shrink",
            Self::FlexBasis => "flex-basis",
            Self::AlignSelf => "align-self",
            Self::Order => "order",
            Self::Flex => "flex",
            Self::Gap => "gap",
            Self::GridTemplateColumns => "grid-template-columns",
            Self::GridTemplateRows => "grid-template-rows",
            Self::GridColumn => "grid-column",
            Self::GridRow => "grid-row",
            Self::Colspan => "colspan",
            Self::Rowspan => "rowspan",
            Self::Top => "top",
            Self::Right => "right",
            Self::Bottom => "bottom",
            Self::Left => "left",
            Self::Transform => "transform",
            Self::Transition => "transition",
            Self::Animation => "animation",
            Self::Visibility => "visibility",
            Self::ZIndex => "z-index",
        }
    }
}
