//! Rust 代码生成器
//!
//! Phase 1: 将编译单元（元素树 + CSS 规则 + JS 处理器）生成为 Rust DOM API 代码。

use std::collections::HashMap;

use crate::html::HtmlElement;
use crate::js::EventHandler;
use crate::variable::VarAssignment;

/// 代码生成器
pub struct CodeGenerator;

impl CodeGenerator {
    /// 生成 main() 函数体
    pub fn generate_main_body(
        assignments: &[VarAssignment],
        matched_styles: &[(String, String)],
        handlers: &[EventHandler],
    ) -> String {
        let mut code = String::new();

        // === HTML 元素构建代码 ===
        code.push_str("    // ====== Compiled from index.html ======\n\n");

        let mut var_names: Vec<(String, String)> = Vec::new();
        let mut tag_counts: HashMap<String, usize> = HashMap::new();

        for assignment in assignments {
            let el_code = generate_element_code_inner(&assignment.element, &assignment.name, 1, &mut tag_counts);
            code.push_str(&el_code);
            code.push('\n');
            var_names.push((assignment.name.clone(), assignment.element.attributes.get("id").cloned().unwrap_or_default()));
        }

        // === 挂载到 body ===
        code.push_str("    // ====== Mount to body ======\n\n");
        for (var_name, _) in &var_names {
            code.push_str(&format!("    doc.borrow().body().borrow_mut().append_child({}.clone());\n", var_name));
        }
        code.push('\n');

        // === 应用样式 ===
        code.push_str("    // ====== Compiled from style.css ======\n\n");
        for (var_name, style_str) in matched_styles {
            let escaped = style_str.replace('\\', "\\\\").replace('"', "\\\"");
            code.push_str(&format!("    {}.borrow_mut().set_style(\"{}\");\n", var_name, escaped));
        }
        code.push('\n');

        // === 事件处理器 ===
        code.push_str("    // ====== Compiled from app.js ======\n\n");
        for handler in handlers {
            for cv in &handler.cloned_vars {
                let base = cv.trim_end_matches("_clone");
                code.push_str(&format!("    let {} = {}.clone();\n", cv, base));
            }
            for sv_name in &handler.shared_vars {
                code.push_str(&format!("    let {}_clone = {}.clone();\n", sv_name, sv_name));
            }
            code.push_str(&format!(
                "    {}.borrow_mut().add_event_listener(\"{}\", Box::new(move |_: &dom::Event| {{\n",
                handler.element_var, handler.event_type
            ));
            for line in handler.body_code.lines() {
                code.push_str(&format!("        {}\n", line));
            }
            code.push_str("    }));\n\n");
        }

        // === 启动 ===
        code.push_str("    // ====== Start rendering ======\n\n");
        code.push_str("    window.run();\n");

        code
    }
}

/// 为元素树生成 DOM 构建代码
pub fn generate_element_code(
    el: &HtmlElement,
    var_name: &str,
    depth: usize,
    tag_counts: &mut HashMap<String, usize>,
) -> String {
    generate_element_code_inner(el, var_name, depth, tag_counts)
}

/// 生成完整 main.rs
pub fn generate_full_source(
    assignments: &[VarAssignment],
    matched_styles: &[(String, String)],
    handlers: &[EventHandler],
) -> String {
    let body = CodeGenerator::generate_main_body(assignments, matched_styles, handlers);
    let mut output = String::new();
    output.push_str("//! Generated by rust-test compiler\n\n");
    output.push_str("use render_wgpu::WebWindow;\n\n");
    output.push_str("fn main() {\n");
    output.push_str(&body);
    output.push_str("}\n");
    output
}

// ── 内部 ──

fn generate_element_code_inner(
    el: &HtmlElement,
    var_name: &str,
    depth: usize,
    tag_counts: &mut HashMap<String, usize>,
) -> String {
    let indent = "    ".repeat(depth);
    let mut code = String::new();

    code.push_str(&format!("{}let {} = doc.borrow().create_element(\"{}\");\n", indent, var_name, el.tag));

    for (key, value) in &el.attributes {
        code.push_str(&format!("{}{}.borrow_mut().set_attribute(\"{}\", \"{}\");\n",
            indent, var_name, key, value.replace('\\', "\\\\").replace('"', "\\\"")));
    }

    if !el.text_content.is_empty() {
        let escaped = el.text_content.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("{}{}.borrow_mut().set_text_content(\"{}\");\n", indent, var_name, escaped));
    }

    for child in &el.children {
        let child_name = crate::variable::generate_var_name(child, tag_counts);
        code.push_str(&generate_element_code_inner(child, &child_name, depth + 1, tag_counts));
        code.push_str(&format!("{}{}.borrow_mut().append_child({}.clone());\n", indent, var_name, child_name));
    }

    code
}
