//! # compiler — HTML+CSS+JS → Rust 编译器
//!
//! Phase 0: 简化版编译器，将简单前端项目转为 Rust DOM API 代码。
//! 通过 build.rs 集成到 cargo 构建流程中。
//!
//! # 使用
//!
//! ```rust,no_run
//! let code = compiler::compile("index.html", "style.css", "app.js");
//! std::fs::write("src/main.rs", code).unwrap();
//! ```

pub mod html;
pub mod css;
pub mod js;
pub mod parser;
pub mod analyzer;
pub mod codegen;
pub mod builtins;
pub mod canvas_codegen;

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub use html::HtmlElement;
pub use parser::{Parser, CompilationUnit, SourceFile, SourceKind};
pub use analyzer::{Analyzer, AnalysisResult, VariableInfo, VariableKind, FunctionCall, DomOperation};
pub use builtins::{
    BuiltinMapping, all_builtins, lookup_builtin,
    typed_array_mappings, async_mappings, class_mappings, phase2_builtins,
    object_mappings, history_mappings, location_mappings,
    url_mappings, date_mappings, phase3_builtins,
};
pub use canvas_codegen::{
    canvas_mappings, compile_canvas_call, is_canvas_call,
};

/// 分配给元素的变量名
#[derive(Debug, Clone)]
pub struct VarAssignment {
    pub name: String,
    pub element: HtmlElement,
}

/// 编译选项
#[derive(Debug, Clone)]
pub struct CompileOptions {
    /// 窗口标题
    pub title: String,
    /// 窗口宽度（逻辑像素）
    pub width: u32,
    /// 窗口高度（逻辑像素）
    pub height: u32,
}

impl Default for CompileOptions {
    fn default() -> Self {
        Self {
            title: "Demo".into(),
            width: 800,
            height: 600,
        }
    }
}

/// 编译为 main() 函数体（用于 include! 方式，使用默认选项）
pub fn compile_body(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_body_with_options(html_path, css_path, js_path, &CompileOptions::default())
}

/// 编译为 main() 函数体（可配置窗口参数）
///
/// CSS/JS 路径为空字符串时视为"无此文件"，使用空内容代替。
pub fn compile_body_with_options(html_path: &str, css_path: &str, js_path: &str, opts: &CompileOptions) -> String {
    // 读取源文件（空路径 → 空内容）
    let html_src = fs::read_to_string(html_path)
        .unwrap_or_else(|e| panic!("Cannot read HTML file '{}': {}", html_path, e));
    let css_src = if css_path.is_empty() {
        String::new()
    } else {
        fs::read_to_string(css_path)
            .unwrap_or_else(|e| panic!("Cannot read CSS file '{}': {}", css_path, e))
    };
    let js_src = if js_path.is_empty() {
        String::new()
    } else {
        fs::read_to_string(js_path)
            .unwrap_or_else(|e| panic!("Cannot read JS file '{}': {}", js_path, e))
    };

    // === Phase 1: 解析 HTML → 元素树 ===
    let elements = html::parse_html(&html_src);

    // === Phase 2: 分配变量名（仅顶层元素，用于代码生成）===
    let root_assignments = assign_root_variable_names(&elements);

    // === Phase 2b: 完整元素列表（含子元素）用于 CSS/JS 匹配 ===
    let all_element_vars: Vec<(String, HtmlElement)> = build_all_element_vars(&elements);

    // === Phase 3: 解析 CSS → 匹配元素 ===
    let css_rules = css::parse_css(&css_src);
    let matched_styles = css::match_css_to_elements(&css_rules, &elements, &all_element_vars);

    // === Phase 4: 编译 JS → 事件处理器 + 共享状态 ===
    let (handlers, shared_state) = js::compile_js(&js_src, &all_element_vars, &css_rules);

    // === Phase 5: 生成 main() 函数体 ===
    generate_main_body_inner(&root_assignments, &matched_styles, &handlers, &css_rules, opts, &shared_state)
}

/// 编译 HTML+CSS+JS 为完整可编译的 main.rs（使用默认选项）
pub fn compile(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_with_options(html_path, css_path, js_path, &CompileOptions::default())
}

/// 编译 HTML+CSS+JS 为完整可编译的 main.rs（可配置窗口参数）
pub fn compile_with_options(html_path: &str, css_path: &str, js_path: &str, opts: &CompileOptions) -> String {
    let body = compile_body_with_options(html_path, css_path, js_path, opts);
    let mut output = String::new();
    output.push_str("//! Generated by rust-test compiler\n\n");
    output.push_str("use render_wgpu::WebWindow;\n\n");
    output.push_str("fn main() {\n");
    output.push_str(&body);
    output.push_str("}\n");
    output
}

/// 为 HTML 元素树分配变量名（递归，含子元素）
///
/// 命名规则：
/// - 有 id 的用 id（`id="inc-btn"` → `inc_btn`）
/// - 有 class 的用第一个 class
/// - 否则用 tag 名（重复则加数字后缀）
fn assign_variable_names(elements: &[HtmlElement]) -> Vec<VarAssignment> {
    let mut result = Vec::new();
    let mut tag_counts: HashMap<String, usize> = HashMap::new();
    collect_recursive(elements, &mut tag_counts, &mut result);
    result
}

/// 仅为顶层元素分配变量名（非递归，用于代码生成）
pub(crate) fn assign_root_variable_names(elements: &[HtmlElement]) -> Vec<VarAssignment> {
    let mut result = Vec::new();
    let mut tag_counts: HashMap<String, usize> = HashMap::new();
    for el in elements {
        let name = generate_var_name(el, &mut tag_counts);
        result.push(VarAssignment {
            name: name.clone(),
            element: el.clone(),
        });
    }
    result
}

/// 构建完整元素列表（含子元素）用于 CSS/JS 匹配
pub(crate) fn build_all_element_vars(elements: &[HtmlElement]) -> Vec<(String, HtmlElement)> {
    let all = assign_variable_names(elements);
    all.into_iter().map(|a| (a.name, a.element)).collect()
}

/// 递归收集所有元素（含子元素）并分配变量名
fn collect_recursive(
    elements: &[HtmlElement],
    tag_counts: &mut HashMap<String, usize>,
    result: &mut Vec<VarAssignment>,
) {
    for el in elements {
        let name = generate_var_name(el, tag_counts);
        result.push(VarAssignment {
            name: name.clone(),
            element: el.clone(),
        });
        collect_recursive(&el.children, tag_counts, result);
    }
}

/// 为单个元素生成变量名
fn generate_var_name(el: &HtmlElement, tag_counts: &mut HashMap<String, usize>) -> String {
    // 优先用 id
    if let Some(id) = el.attributes.get("id") {
        // 将 id 中的连字符转为下划线
        let name = id.replace('-', "_");
        return name;
    }

    // 其次用 class
    if let Some(class) = el.attributes.get("class") {
        if let Some(first_class) = class.split_whitespace().next() {
            let name = first_class.replace('-', "_");
            return name;
        }
    }

    // 否则用 tag 名
    let count = tag_counts.entry(el.tag.clone()).or_insert(0);
    *count += 1;
    if *count == 1 {
        el.tag.clone()
    } else {
        format!("{}_{}", el.tag, count)
    }
}

/// 为元素树生成 DOM 构建代码（递归）
pub(crate) fn generate_element_code_inner(
    el: &HtmlElement,
    var_name: &str,
    depth: usize,
    tag_counts: &mut HashMap<String, usize>,
) -> String {
    let indent = "    ".repeat(depth);
    let mut code = String::new();

    code.push_str(&format!("{}let {} = doc.borrow().create_element(\"{}\");\n", indent, var_name, el.tag));

    // 设置所有属性
    for (key, value) in &el.attributes {
        code.push_str(&format!("{}{}.borrow_mut().set_attribute(\"{}\", \"{}\");\n",
            indent, var_name, key, value.replace('\\', "\\\\").replace('"', "\\\"")));
    }

    // 设置文本内容
    if !el.text_content.is_empty() {
        let escaped = el.text_content.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("{}{}.borrow_mut().set_text_content(\"{}\");\n",
            indent, var_name, escaped));
    }

    // 递归子元素
    for child in &el.children {
        let child_name = generate_var_name(child, tag_counts);
        code.push_str(&generate_element_code_inner(child, &child_name, depth + 1, tag_counts));
        code.push_str(&format!("{}{}.borrow_mut().append_child({}.clone());\n",
            indent, var_name, child_name));
    }

    code
}

/// 生成 main() 函数体（供 include! 使用）
pub(crate) fn generate_main_body_inner(
    assignments: &[VarAssignment],
    matched_styles: &[(String, String)],
    handlers: &[js::EventHandler],
    css_rules: &[css::CssRule],
    opts: &CompileOptions,
    shared_state: &[js::SharedStateVar],
) -> String {
    let mut code = String::new();

    // === 创建窗口 ===
    code.push_str(&format!(
        "    let mut window = WebWindow::new(\"{}\", {}, {});\n",
        opts.title.replace('\\', "\\\\").replace('"', "\\\""),
        opts.width,
        opts.height,
    ));
    code.push_str("    let doc = window.document();\n\n");

    // === 生成元素构建代码 ===
    code.push_str("    // ====== Compiled from index.html ======\n\n");

    let mut var_names: Vec<(String, String)> = Vec::new(); // (var_name, element_id_or_class)
    let mut tag_counts: HashMap<String, usize> = HashMap::new();

    for assignment in assignments {
        let el_code = generate_element_code_inner(&assignment.element, &assignment.name, 1, &mut tag_counts);
        code.push_str(&el_code);
        code.push('\n');

        // 收集变量名用于挂载到 body
        var_names.push((assignment.name.clone(), assignment.element.attributes.get("id").cloned().unwrap_or_default()));
    }

    // === 挂载到 body ===
    code.push_str("    // ====== Mount to body ======\n\n");
    for (var_name, _) in &var_names {
        code.push_str(&format!("    doc.borrow().body().borrow_mut().append_child({}.clone());\n", var_name));
    }
    code.push('\n');

    // === 应用样式 ===
    code.push_str("    // ====== Compiled from style.css ======\n\n");
    for (var_name, style_str) in matched_styles {
        let escaped = style_str.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("    {}.borrow_mut().set_style(\"{}\");\n", var_name, escaped));
    }

    // 应用 body 样式（body 由 Document::new() 原生创建，不经过 HTML 解析）
    for rule in css_rules {
        if rule.selector.trim() == "body" && !rule.declarations.is_empty() {
            let style_str = rule.declarations.iter()
                .map(|(k, v)| format!("{}: {}", k, v))
                .collect::<Vec<_>>()
                .join("; ");
            let escaped = style_str.replace('\\', "\\\\").replace('"', "\\\"");
            code.push_str(&format!("    doc.borrow().body().borrow_mut().set_style(\"{}\");\n", escaped));
        }
    }
    code.push('\n');

    // === 生成共享状态变量 ===
    if !shared_state.is_empty() {
        code.push_str("    // 共享状态（JS 全局变量）\n");
        for sv in shared_state {
            code.push_str(&format!(
                "    let {} = std::rc::Rc::new(std::cell::RefCell::new({}i32));\n",
                sv.name, sv.initial_value
            ));
        }
        code.push('\n');
    }

    // === 生成事件处理器 ===
    code.push_str("    // ====== Compiled from app.js ======\n\n");

    for handler in handlers {
        // 生成 clone 变量（DOM 元素）
        for cv in &handler.cloned_vars {
            let base = cv.trim_end_matches("_clone");
            code.push_str(&format!("    let {} = {}.clone();\n", cv, base));
        }

        // 生成 clone 变量（共享状态 Rc）
        for sv_name in &handler.shared_vars {
            code.push_str(&format!("    let {}_clone = {}.clone();\n", sv_name, sv_name));
        }

        // 生成 add_event_listener 调用
        code.push_str(&format!(
            "    {}.borrow_mut().add_event_listener(\"{}\", Box::new(move |_: &dom::Event| {{\n",
            handler.element_var, handler.event_type
        ));

        // 处理器体
        for line in handler.body_code.lines() {
            code.push_str(&format!("        {}\n", line));
        }

        code.push_str("    }));\n\n");
    }

    // === 启动 ===
    code.push_str("    // ====== Start rendering ======\n\n");
    code.push_str("    window.run();\n");

    code
}

/// 编译为完整 main.rs 并写入输出文件
pub fn compile_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}

/// 编译为 main() 函数体并写入输出文件（用于 include! 方式）
pub fn compile_body_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile_body(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}

// ═══════════════════════════════════════════════════════════════════
// 项目级编译 API（从 CLI 移入）
// ═══════════════════════════════════════════════════════════════════

/// `compile_project` 的输出。
pub struct CompileProjectOutput {
    /// 生成的 Rust 源代码（完整 main.rs）
    pub rust_code: String,
    /// 找到的 HTML 文件路径
    pub html_path: PathBuf,
    /// 使用的 CSS 文件路径
    pub css_path: Option<PathBuf>,
    /// 使用的 JS 文件路径
    pub js_path: Option<PathBuf>,
}

/// 从项目目录编译：找 HTML → 提取引用 → 读 CSS/JS → 编译。
///
/// `input_dir` 应包含 HTML/CSS/JS 源文件。
/// 优先使用 index.html，否则使用第一个 .html 文件。
/// CSS/JS 从 HTML 的 `<link>`/`<script>` 标签中提取。
pub fn compile_project(
    input_dir: &Path,
    opts: &CompileOptions,
) -> Result<CompileProjectOutput, String> {
    // 1. 找 HTML 入口
    let html_path = find_html_file(input_dir)?;

    // 2. 读 HTML 并提取 CSS/JS 引用
    let html_src = fs::read_to_string(&html_path)
        .map_err(|e| format!("cannot read {}: {e}", html_path.display()))?;
    let (css_refs, js_refs) = html::extract_references(&html_src);

    // 3. 解析 CSS/JS 路径
    let css_path = resolve_ref(input_dir, &css_refs, "CSS");
    let js_path = resolve_ref(input_dir, &js_refs, "JS");

    // 4. 生成 Rust 代码
    let css_path_str = css_path
        .as_ref()
        .map_or(String::new(), |p| p.to_string_lossy().to_string());
    let js_path_str = js_path
        .as_ref()
        .map_or(String::new(), |p| p.to_string_lossy().to_string());
    let rust_code = compile_with_options(
        &html_path.to_string_lossy(),
        &css_path_str,
        &js_path_str,
        opts,
    );

    Ok(CompileProjectOutput {
        rust_code,
        html_path,
        css_path,
        js_path,
    })
}

/// 编译项目并写入输出目录（创建完整的 Cargo 项目）。
///
/// 输出目录将包含 `src/main.rs` 和 `Cargo.toml`。
/// `workspace_root` 用于计算 Cargo.toml 中依赖 crate 的相对路径。
pub fn compile_project_to_dir(
    input_dir: &Path,
    output_dir: &Path,
    name: &str,
    workspace_root: &Path,
    opts: &CompileOptions,
) -> Result<(), String> {
    let output = compile_project(input_dir, opts)?;

    // 创建输出目录
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)
        .map_err(|e| format!("cannot create {}: {e}", src_dir.display()))?;

    // 写 main.rs
    fs::write(src_dir.join("main.rs"), &output.rust_code)
        .map_err(|e| format!("cannot write main.rs: {e}"))?;

    // 写 Cargo.toml
    let renderer_rel = rel_path(
        output_dir,
        &workspace_root.join("crates").join("renderer"),
    );
    let dom_rel = rel_path(output_dir, &workspace_root.join("crates").join("dom"));
    let cargo_toml = format!(
        "[workspace]\n\
         \n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [dependencies]\n\
         renderer = {{ path = \"{renderer_rel}\" }}\n\
         dom = {{ path = \"{dom_rel}\" }}\n",
    );
    fs::write(output_dir.join("Cargo.toml"), &cargo_toml)
        .map_err(|e| format!("cannot write Cargo.toml: {e}"))?;

    Ok(())
}

// ── 内部工具函数 ──

/// 在目录中找 HTML 入口文件：优先 index.html，否则第一个 .html。
fn find_html_file(dir: &Path) -> Result<PathBuf, String> {
    let default = dir.join("index.html");
    if default.exists() {
        return Ok(default);
    }
    find_file_by_ext(dir, "html").ok_or_else(|| format!("no .html file found in {}", dir.display()))
}

/// 在目录中按扩展名查找第一个匹配的文件。
fn find_file_by_ext(dir: &Path, ext: &str) -> Option<PathBuf> {
    let mut matches: Vec<PathBuf> = fs::read_dir(dir)
        .ok()?
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_file())
        .filter(|p| p.extension().map(|e| e.to_str()) == Some(Some(ext)))
        .collect();
    matches.sort();
    matches.into_iter().next()
}

/// 从 HTML 提取的文件引用列表中解析第一个存在的文件路径。
fn resolve_ref(input_dir: &Path, refs: &[String], label: &str) -> Option<PathBuf> {
    if refs.is_empty() {
        eprintln!("warning: no {label} file referenced in HTML");
        return None;
    }
    for r in refs {
        let candidate = input_dir.join(r);
        if candidate.exists() {
            return Some(candidate);
        }
        eprintln!("warning: {label} file not found: {}", candidate.display());
    }
    eprintln!("warning: no {label} file found for references: {:?}", refs);
    None
}

/// 计算从一个目录到另一个路径的相对路径（始终使用正斜杠）。
fn rel_path(from: &Path, to: &Path) -> String {
    let from_abs = from.canonicalize().unwrap_or_else(|_| {
        if let Some(parent) = from.parent() {
            if let Ok(parent_abs) = parent.canonicalize() {
                return parent_abs.join(from.file_name().unwrap_or_default());
            }
        }
        from.to_path_buf()
    });

    let to_abs = to.canonicalize().unwrap_or_else(|_| to.to_path_buf());

    let from_parts: Vec<_> = from_abs.components().collect();
    let to_parts: Vec<_> = to_abs.components().collect();

    let common = from_parts
        .iter()
        .zip(to_parts.iter())
        .take_while(|(a, b)| a == b)
        .count();

    let up_count = from_parts.len() - common;
    let mut result = String::new();
    for _ in 0..up_count {
        result.push_str("../");
    }
    for comp in &to_parts[common..] {
        result.push_str(&comp.as_os_str().to_string_lossy());
        result.push('/');
    }
    if result.ends_with('/') {
        result.pop();
    }

    result.replace('\\', "/")
}

#[cfg(test)]
#[path = "../test/lib_test.rs"]
mod tests;
