//! # compiler — HTML+CSS+JS → Rust 编译器
//!
//! Phase 0: 简化版编译器，将简单前端项目转为 Rust DOM API 代码。

pub mod html;
pub mod css;
pub mod js;
pub mod parser;
pub mod analyzer;
pub mod codegen;
pub mod builtins;
pub mod canvas_codegen;
pub mod config;
pub mod variable;
pub mod pipeline;
pub mod resolve;

use std::fs;
use std::path::{Path, PathBuf};

// ── re-export ──

pub use html::HtmlElement;
pub use parser::{Parser, CompilationUnit, SourceFile, SourceKind};
pub use analyzer::{Analyzer, AnalysisResult, VariableInfo, VariableKind, FunctionCall, DomOperation};
pub use builtins::{
    BuiltinMapping, all_builtins, lookup_builtin,
    typed_array_mappings, async_mappings, class_mappings, phase2_builtins,
    object_mappings, history_mappings, location_mappings,
    url_mappings, date_mappings, phase3_builtins,
};
pub use canvas_codegen::{
    canvas_mappings, compile_canvas_call, is_canvas_call,
};
pub use config::{CompileInput, ResolvedConfig};
pub use pipeline::{compile, compile_body, compile_body_with_options, compile_to_file, compile_body_to_file};

// ── 项目级编译 ──

/// 编译项目并写入输出目录，生成完整的可构建 Cargo 项目。
pub fn compile_project_to_dir(input: CompileInput) -> Result<ResolvedConfig, String> {
    let resolved = config::resolve(&input)?;
    let output = compile_project(&resolved.input_dir, &resolved.entry)?;

    let output_dir = &resolved.output_dir;
    let src_dir = output_dir.join("src");
    fs::create_dir_all(&src_dir)
        .map_err(|e| format!("cannot create {}: {e}", src_dir.display()))?;

    fs::write(src_dir.join("main.rs"), &output.rust_code)
        .map_err(|e| format!("cannot write main.rs: {e}"))?;

    let workspace_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let renderer_rel = resolve::rel_path(
        output_dir,
        &workspace_root.join("crates").join("renderer"),
    );
    let dom_rel = resolve::rel_path(output_dir, &workspace_root.join("crates").join("dom"));
    let cargo_toml = format!(
        "[workspace]\n\
         \n\
         [package]\n\
         name = \"{}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [dependencies]\n\
         renderer = {{ path = \"{renderer_rel}\" }}\n\
         dom = {{ path = \"{dom_rel}\" }}\n",
        resolved.name,
    );
    fs::write(output_dir.join("Cargo.toml"), &cargo_toml)
        .map_err(|e| format!("cannot write Cargo.toml: {e}"))?;

    Ok(resolved)
}

// ── 内部 ──

struct CompileProjectOutput {
    rust_code: String,
}

/// 从输入目录编译：找 HTML 入口 → 读文件 → 调用 pipeline
fn compile_project(input_dir: &Path, entry: &str) -> Result<CompileProjectOutput, String> {
    let html_path = resolve::find_html_file(input_dir, entry)?;
    let html_src = fs::read_to_string(&html_path)
        .map_err(|e| format!("cannot read {}: {e}", html_path.display()))?;

    let (css_refs, js_refs) = html::extract_references(&html_src);
    let css_path = resolve_ref(input_dir, &css_refs, "CSS");
    let js_path = resolve_ref(input_dir, &js_refs, "JS");

    let css_path_str = css_path.as_ref().map_or(String::new(), |p| p.to_string_lossy().to_string());
    let js_path_str = js_path.as_ref().map_or(String::new(), |p| p.to_string_lossy().to_string());

    let rust_code = compile_body(
        &html_path.to_string_lossy(),
        &css_path_str,
        &js_path_str,
    );
    let main_rs = format!(
        "//! Generated by rust-test compiler\n\nuse render_wgpu::WebWindow;\n\nfn main() {{\n{}\n}}\n",
        rust_code
    );

    Ok(CompileProjectOutput { rust_code: main_rs })
}

fn resolve_ref(input_dir: &Path, refs: &[String], _label: &str) -> Option<PathBuf> {
    refs.first().map(|r| input_dir.join(r))
}
