//! 编译管线（精简版 — 宏方式）
//!
//! 读取 HTML/CSS/JS 源文件，生成嵌入 `html!`/`css!`/`style!` 宏的 Rust 代码。
//! HTML/CSS 解析由 proc-macro 在编译期完成，compiler 仅负责模板生成和 JS 编译。

use crate::config::ResolvedConfig;
use crate::resolve;
use std::path::Path;

// ── 文件级 API（向后兼容）──

/// 编译为 `main()` 函数体（宏方式）。
/// 生成的代码依赖 `ruft-macro`、`dom`、`render_wgpu`。
pub fn compile_body(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_body_with_options(html_path, css_path, js_path, "Demo", 800, 600)
}

/// 编译为 `main()` 函数体（宏方式，自定义窗口参数）。
pub fn compile_body_with_options(
    html_path: &str,
    css_path: &str,
    js_path: &str,
    title: &str,
    width: u32,
    height: u32,
) -> String {
    let html_src = std::fs::read_to_string(html_path)
        .unwrap_or_else(|e| panic!("无法读取 HTML 文件 '{}': {}", html_path, e));
    let input_dir = Path::new(html_path).parent().unwrap_or(Path::new("."));

    let resources = extract_resources(&html_src, input_dir);

    let css_content = read_file_or_empty(css_path);
    let js_content = read_file_or_empty(js_path);

    // 编译 JS → Rust 事件处理器
    let js_handlers = compile_js(&js_content);

    generate_body_code(title, width, height, &resources.body_html, &css_content, &js_handlers)
}

/// 编译为完整 `main.rs`。
pub fn compile(html_path: &str, css_path: &str, js_path: &str) -> String {
    let body = compile_body(html_path, css_path, js_path);
    format!(
        "//! Generated by ruft compiler (macro mode)\n\nuse render_wgpu::WebWindow;\nuse ruft_macro::{{html, style}};\nuse std::cell::RefCell;\nuse std::rc::Rc;\n\nfn main() {{\n{}\n}}\n",
        body
    )
}

/// 编译完整 main.rs 并写入文件。
pub fn compile_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile(html_path, css_path, js_path);
    if let Some(parent) = Path::new(output_path).parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("无法写入输出文件 '{}': {}", output_path, e));
}

/// 编译函数体并写入文件。
pub fn compile_body_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile_body(html_path, css_path, js_path);
    if let Some(parent) = Path::new(output_path).parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("无法写入输出文件 '{}': {}", output_path, e));
}

// ── 项目级 API ──

/// 编译项目到输出目录（宏方式 — 新版）。
///
/// 生成：
/// - `src/main.rs` — 使用 `html!`/`style!` 宏的 Rust 入口
/// - `Cargo.toml` — 依赖 `dom`, `render_wgpu`, `ruft-macro`
pub fn compile_project_to_dir(resolved: &ResolvedConfig) -> Result<(), String> {
    let html_path = resolve::find_html_file(&resolved.input_dir, &resolved.entry)?;
    let input_dir = &resolved.input_dir;

    let html_content = std::fs::read_to_string(&html_path)
        .map_err(|e| format!("读取 HTML 失败: {}", e))?;

    let resources = extract_resources(&html_content, input_dir);

    // 读取 CSS 文件
    let mut css_content = String::new();
    for file in &resources.css_files {
        let path = input_dir.join(file);
        match std::fs::read_to_string(&path) {
            Ok(c) => {
                css_content.push_str(&c);
                css_content.push('\n');
            }
            Err(e) => eprintln!("警告: 无法读取 CSS 文件 '{}': {}", file, e),
        }
    }

    // 编译 JS 文件
    let mut js_code = String::new();
    for file in &resources.js_files {
        let path = input_dir.join(file);
        match std::fs::read_to_string(&path) {
            Ok(js) => {
                js_code.push_str(&compile_js(&js));
                js_code.push('\n');
            }
            Err(e) => eprintln!("警告: 无法读取 JS 文件 '{}': {}", file, e),
        }
    }

    // 生成 main.rs
    let main_rs = generate_main_rs(resolved, &resources.body_html, &css_content, &js_code);

    // 生成 Cargo.toml
    let cargo_toml = generate_cargo_toml(resolved);

    // 写入
    let src_dir = resolved.output_dir.join("src");
    std::fs::create_dir_all(&src_dir)
        .map_err(|e| format!("创建 src 目录失败: {}", e))?;
    std::fs::write(src_dir.join("main.rs"), &main_rs)
        .map_err(|e| format!("写入 main.rs 失败: {}", e))?;
    std::fs::write(resolved.output_dir.join("Cargo.toml"), &cargo_toml)
        .map_err(|e| format!("写入 Cargo.toml 失败: {}", e))?;

    Ok(())
}

// ── 内部实现 ──

struct HtmlResources {
    body_html: String,
    css_files: Vec<String>,
    js_files: Vec<String>,
}

fn extract_resources(html: &str, _input_dir: &Path) -> HtmlResources {
    let body_html = extract_body(html).unwrap_or_default();
    let css_files = extract_refs(html, "stylesheet", "href");
    let js_files = extract_refs(html, "<script", "src")
        .into_iter()
        .filter(|s| !s.is_empty())
        .collect();

    HtmlResources {
        body_html,
        css_files,
        js_files,
    }
}

fn extract_body(html: &str) -> Option<String> {
    let start = html.find("<body")?;
    let start = html[start..].find('>').map(|i| start + i + 1)?;
    let end = html[start..].find("</body>").map(|i| start + i)?;
    let body = html[start..end].trim().to_string();
    // 过滤 <script> 和 <style> 标签（它们不是 DOM 元素）
    let body = strip_tag(&body, "script");
    let body = strip_tag(&body, "style");
    // 将无引号文本节点转为 Rust 字符串字面量
    Some(quote_text_nodes(&body))
}

/// 移除指定标签及其内容（如 <script>...</script>）
fn strip_tag(html: &str, tag: &str) -> String {
    let open = format!("<{}", tag);
    let close = format!("</{}>", tag);
    let mut result = String::new();
    let mut remaining = html;
    while let Some(start) = remaining.find(&open) {
        result.push_str(&remaining[..start]);
        if let Some(end) = remaining[start..].find(&close) {
            let end = start + end + close.len();
            remaining = &remaining[end..];
        } else {
            remaining = &remaining[start + open.len()..];
        }
    }
    result.push_str(remaining);
    result
}

/// 将 HTML 文本节点转为 Rust 字符串字面量
/// <h1>Counter</h1> → <h1>"Counter"</h1>
fn quote_text_nodes(html: &str) -> String {
    let mut result = String::new();
    let chars: Vec<char> = html.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '>' {
            result.push('>');
            i += 1;
            // 收集直到下一个 '<' 的文本
            let mut text = String::new();
            while i < chars.len() && chars[i] != '<' {
                text.push(chars[i]);
                i += 1;
            }
            let trimmed = text.trim();
            if !trimmed.is_empty() {
                // 如果已经是 Rust 字面量或表达式，保持原样
                if trimmed.starts_with('"') || trimmed.starts_with('{') {
                    result.push_str(&text);
                } else {
                    // 替换为带引号的版本（保留前导空白）
                    let leading = text.len() - text.trim_start().len();
                    let trailing = text.len() - text.trim_end().len();
                    result.push_str(&text[..leading]);
                    result.push('"');
                    result.push_str(trimmed);
                    result.push('"');
                    result.push_str(&text[text.len() - trailing..]);
                }
            } else {
                result.push_str(&text);
            }
        } else {
            result.push(chars[i]);
            i += 1;
        }
    }
    result
}

fn extract_refs(html: &str, tag_pattern: &str, attr: &str) -> Vec<String> {
    let mut refs = Vec::new();
    for line in html.lines() {
        if line.contains(tag_pattern) && line.contains(&format!("{}=", attr)) {
            if let Some(start) = line.find(&format!("{}=", attr)) {
                let rest = &line[start + attr.len() + 1..];
                let delim = rest.chars().next().unwrap_or('"');
                let rest = &rest[1..];
                if let Some(end) = rest.find(delim) {
                    refs.push(rest[..end].to_string());
                }
            }
        }
    }
    refs
}

fn read_file_or_empty(path: &str) -> String {
    if path.is_empty() {
        return String::new();
    }
    std::fs::read_to_string(path).unwrap_or_default()
}

fn compile_js(js: &str) -> String {
    if js.trim().is_empty() {
        return String::new();
    }
    // 委托给现有的 JS 编译器
    let (handlers, shared_state) = crate::js::compile_js(js, &[], &[]);
    crate::js::generate_handler_code(&handlers, &shared_state)
}

// ── 代码生成 ──

fn generate_body_code(
    title: &str,
    width: u32,
    height: u32,
    body_html: &str,
    css_content: &str,
    js_code: &str,
) -> String {
    let body_styles = extract_body_styles(css_content);

    format!(
        r#"    let mut window = WebWindow::new("{title}", {width}, {height});
    let doc = window.document();

    // ── HTML 结构（编译期 proc-macro 展开）──
    let (root, refs) = html! {{
{body_html}
    }}(&doc);

    // ── Body 样式 ──
    doc.borrow().body().borrow_mut().set_style(
        style! {{{body_styles}}}
    );

{js_code}
    // ── 挂载到 body ──
    doc.borrow().body().borrow_mut().append_child(root);

    // ── 启动渲染 ──
    window.run();"#,
        title = title,
        width = width,
        height = height,
        body_html = indent(body_html, 8),
        body_styles = body_styles,
        js_code = indent(js_code, 4),
    )
}

fn generate_main_rs(
    resolved: &ResolvedConfig,
    body_html: &str,
    css_content: &str,
    js_code: &str,
) -> String {
    let body = generate_body_code(
        &resolved.title,
        resolved.width,
        resolved.height,
        body_html,
        css_content,
        js_code,
    );

    // 根据是否有 JS 代码决定 import
    let extra_imports = if js_code.trim().is_empty() {
        String::new()
    } else {
        "use std::cell::RefCell;\nuse std::rc::Rc;\n".to_string()
    };

    format!(
        r#"//! Generated by ruft compiler (macro mode)

use render_wgpu::WebWindow;
use ruft_macro::{{html, style}};
{extra_imports}
fn main() {{
{}
}}
"#,
        body
    )
}

fn extract_body_styles(css: &str) -> String {
    if let Some(start) = css.find("body") {
        if let Some(brace_start) = css[start..].find('{') {
            let content_start = start + brace_start + 1;
            if let Some(brace_end) = css[content_start..].find('}') {
                return css[content_start..content_start + brace_end]
                    .trim()
                    .to_string();
            }
        }
    }
    "background: #f5f5f5; font-family: system-ui, sans-serif; margin: 0;".to_string()
}

fn generate_cargo_toml(resolved: &ResolvedConfig) -> String {
    let dom_path = resolve::rel_path(
        &resolved.output_dir,
        &resolve::workspace_root().join("crates/core/dom"),
    );
    let renderer_path = resolve::rel_path(
        &resolved.output_dir,
        &resolve::workspace_root().join("crates/render/render_wgpu"),
    );
    let ruft_macro_path = resolve::rel_path(
        &resolved.output_dir,
        &resolve::workspace_root().join("crates/ruft-macro"),
    );

    format!(
        r#"[workspace]

[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
dom = {{ path = "{dom_path}" }}
render_wgpu = {{ path = "{renderer_path}" }}
ruft-macro = {{ path = "{ruft_macro_path}" }}
"#,
        name = resolved.name,
        dom_path = dom_path.replace('\\', "/"),
        renderer_path = renderer_path.replace('\\', "/"),
        ruft_macro_path = ruft_macro_path.replace('\\', "/"),
    )
}

fn indent(s: &str, spaces: usize) -> String {
    let prefix = " ".repeat(spaces);
    s.lines()
        .map(|line| {
            if line.trim().is_empty() {
                String::new()
            } else {
                format!("{}{}", prefix, line)
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}
