//! 编译管线 —— 将 HTML/CSS/JS 源文件编译为 Rust 代码。
//!
//! 提供两层 API：
//!
//! # 文件级 API（直接指定路径）
//!
//! | 函数 | 说明 |
//! |------|------|
//! | [`compile_body`] | 编译为 `main()` 函数体（不含 `fn main` 包装） |
//! | [`compile_body_with_options`] | 同上，可指定窗口参数 |
//! | [`compile`] | 编译为完整 `main.rs`（含 `fn main` 包装 + use 语句） |
//! | [`compile_with_options`] | 同上，可指定窗口参数 |
//! | [`compile_to_file`] | 编译完整 `main.rs` 并写入文件 |
//! | [`compile_body_to_file`] | 编译函数体并写入文件（for `include!`） |
//!
//! # 编译管线（Phase 0 — 5）
//!
//! ```text
//! Phase 1: html::parse_html()        → 元素树（HtmlElement）
//! Phase 2: variable::assign_*()      → 变量名分配
//! Phase 3: css::parse_css()          → CSS 规则匹配
//! Phase 4: js::compile_js()          → 事件处理器 + 共享状态
//! Phase 5: codegen::generate_*()     → Rust 代码输出
//! ```

use crate::variable;
use crate::{css, html, js};
use std::fs;

// ── 函数体级 API ──

/// 编译为 `main()` 函数体（默认窗口 800×600, title="Demo"）。
pub fn compile_body(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_body_with_options(html_path, css_path, js_path, "Demo", 800, 600)
}

/// 编译为 `main()` 函数体（自定义窗口参数）。
///
/// 从 HTML 中自动发现 CSS/JS；额外的 `css_path`/`js_path` 会合并进去（向后兼容）。
pub fn compile_body_with_options(
    html_path: &str,
    css_path: &str,
    js_path: &str,
    title: &str,
    width: u32,
    height: u32,
) -> String {
    use std::path::Path;

    let html_src = fs::read_to_string(html_path)
        .unwrap_or_else(|e| panic!("Cannot read HTML file '{}': {}", html_path, e));
    let input_dir = Path::new(html_path).parent().unwrap_or(Path::new("."));

    let mut resources = html::parse_html_document(&html_src, input_dir);

    // 向后兼容：额外指定的 CSS/JS 文件也加入来源
    if !css_path.is_empty() {
        resources.css_sources.push(html::CssSource::File(Path::new(css_path).to_path_buf()));
    }
    if !js_path.is_empty() {
        resources.js_sources.push(html::JsSource::File(Path::new(js_path).to_path_buf()));
    }

    compile_resources(&resources, title, width, height)
}

/// 核心管线：从已解析的 [`HtmlResources`] 生成 Rust 代码。
pub(crate) fn compile_resources(
    resources: &html::HtmlResources,
    title: &str,
    width: u32,
    height: u32,
) -> String {
    let elements = &resources.elements;
    let root_assignments = variable::assign_root_variable_names(elements);
    let all_element_vars = variable::build_all_element_vars(elements);

    let css_rules = css::parse_css_sources(&resources.css_sources);
    let matched_styles = css::match_css_to_elements(&css_rules, elements, &all_element_vars);

    let mut handlers = Vec::new();
    let mut shared_state = Vec::new();
    for js_src in &resources.js_sources {
        let js_content = match js_src {
            html::JsSource::File(path) => {
                fs::read_to_string(path).unwrap_or_else(|e| panic!("Cannot read JS '{}': {e}", path.display()))
            }
            html::JsSource::Inline(content) => content.clone(),
        };
        let (h, s) = js::compile_js(&js_content, &all_element_vars, &css_rules);
        handlers.extend(h);
        shared_state.extend(s);
    }

    crate::codegen::CodeGenerator::generate_main_body(
        &root_assignments,
        &matched_styles,
        &handlers,
    )
}

// ── 完整文件级 API ──

/// 编译为完整 `main.rs`（默认窗口参数）。
pub fn compile(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_with_options(html_path, css_path, js_path, "Demo", 800, 600)
}

/// 编译为完整 `main.rs`（自定义窗口参数）。
pub fn compile_with_options(
    html_path: &str,
    css_path: &str,
    js_path: &str,
    title: &str,
    width: u32,
    height: u32,
) -> String {
    let body = compile_body_with_options(html_path, css_path, js_path, title, width, height);
    let mut output = String::new();
    output.push_str("//! Generated by rust-test compiler\n\n");
    output.push_str("use render_wgpu::WebWindow;\n\n");
    output.push_str("fn main() {\n");
    output.push_str(&body);
    output.push_str("}\n");
    output
}

// ── 文件输出 API ──

/// 编译为完整 `main.rs` 并直接写入指定路径。
///
/// 自动创建父目录（如不存在）。
///
/// # Panics
///
/// 写入失败时 panic。
pub fn compile_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}

/// 编译为函数体并写入文件（用于 `include!` 集成方式）。
///
/// 与 [`compile_to_file`] 的区别：输出不含 `fn main` 包装，
/// 由调用方的 `include!` 宏嵌入到自己的 `main()` 中。
///
/// # Panics
///
/// 写入失败时 panic。
pub fn compile_body_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile_body(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}
