//! Rust 代码生成器
//!
//! Phase 1: 将编译单元（元素树 + CSS 规则 + JS 处理器）生成为 Rust DOM API 代码。
//! Phase 2+: 完整表达式编译、优化输出。

use std::collections::HashMap;

use crate::html::HtmlElement;
use crate::js::EventHandler;
use crate::VarAssignment;

/// 代码生成器
pub struct CodeGenerator;

impl CodeGenerator {
    /// 生成 main() 函数体
    pub fn generate_main_body(
        assignments: &[VarAssignment],
        matched_styles: &[(String, String)],
        handlers: &[EventHandler],
    ) -> String {
        crate::generate_main_body_inner(assignments, matched_styles, handlers, &[], &crate::CompileOptions::default(), &[])
    }
}

/// 生成完整 main.rs
pub fn generate_full_source(assignments: &[VarAssignment], matched_styles: &[(String, String)], handlers: &[EventHandler]) -> String {
    let body = CodeGenerator::generate_main_body(assignments, matched_styles, handlers);
    let mut output = String::new();
    output.push_str("//! Generated by toolchain compiler\n\n");
    output.push_str("use renderer::WebWindow;\n\n");
    output.push_str("fn main() {\n");
    output.push_str(&body);
    output.push_str("}\n");
    output
}

/// 为元素树生成 DOM 构建代码
pub fn generate_element_code(
    el: &HtmlElement,
    var_name: &str,
    depth: usize,
    tag_counts: &mut HashMap<String, usize>,
) -> String {
    crate::generate_element_code_inner(el, var_name, depth, tag_counts)
}
