//! # toolchain — HTML+CSS+JS → Rust 编译器
//!
//! Phase 0: 简化版编译器，将简单前端项目转为 Rust DOM API 代码。
//! 通过 build.rs 集成到 cargo 构建流程中。
//!
//! # 使用
//!
//! ```rust,no_run
//! let code = toolchain::compile("index.html", "style.css", "app.js");
//! std::fs::write("src/main.rs", code).unwrap();
//! ```

pub mod html;
pub mod css;
pub mod js;
pub mod parser;
pub mod analyzer;
pub mod codegen;
pub mod builtins;
pub mod canvas_codegen;

use std::collections::HashMap;
use std::fs;

pub use html::HtmlElement;
pub use parser::{Parser, CompilationUnit, SourceFile, SourceKind};
pub use analyzer::{Analyzer, AnalysisResult, VariableInfo, VariableKind, FunctionCall, DomOperation};
pub use builtins::{
    BuiltinMapping, all_builtins, lookup_builtin,
    typed_array_mappings, async_mappings, class_mappings, phase2_builtins,
    object_mappings, history_mappings, location_mappings,
    url_mappings, date_mappings, phase3_builtins,
};
pub use canvas_codegen::{
    canvas_mappings, compile_canvas_call, is_canvas_call,
};

/// 分配给元素的变量名
#[derive(Debug, Clone)]
pub struct VarAssignment {
    pub name: String,
    pub element: HtmlElement,
}

/// 编译选项
#[derive(Debug, Clone)]
pub struct CompileOptions {
    /// 窗口标题
    pub title: String,
    /// 窗口宽度（逻辑像素）
    pub width: u32,
    /// 窗口高度（逻辑像素）
    pub height: u32,
}

impl Default for CompileOptions {
    fn default() -> Self {
        Self {
            title: "Demo".into(),
            width: 800,
            height: 600,
        }
    }
}

/// 编译为 main() 函数体（用于 include! 方式，使用默认选项）
pub fn compile_body(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_body_with_options(html_path, css_path, js_path, &CompileOptions::default())
}

/// 编译为 main() 函数体（可配置窗口参数）
pub fn compile_body_with_options(html_path: &str, css_path: &str, js_path: &str, opts: &CompileOptions) -> String {
    // 读取源文件
    let html_src = fs::read_to_string(html_path)
        .unwrap_or_else(|e| panic!("Cannot read HTML file '{}': {}", html_path, e));
    let css_src = fs::read_to_string(css_path)
        .unwrap_or_else(|e| panic!("Cannot read CSS file '{}': {}", css_path, e));
    let js_src = fs::read_to_string(js_path)
        .unwrap_or_else(|e| panic!("Cannot read JS file '{}': {}", js_path, e));

    // === Phase 1: 解析 HTML → 元素树 ===
    let elements = html::parse_html(&html_src);

    // === Phase 2: 分配变量名（仅顶层元素，用于代码生成）===
    let root_assignments = assign_root_variable_names(&elements);

    // === Phase 2b: 完整元素列表（含子元素）用于 CSS/JS 匹配 ===
    let all_element_vars: Vec<(String, HtmlElement)> = build_all_element_vars(&elements);

    // === Phase 3: 解析 CSS → 匹配元素 ===
    let css_rules = css::parse_css(&css_src);
    let matched_styles = css::match_css_to_elements(&css_rules, &elements, &all_element_vars);

    // === Phase 4: 编译 JS → 事件处理器 + 共享状态 ===
    let (handlers, shared_state) = js::compile_js(&js_src, &all_element_vars, &css_rules);

    // === Phase 5: 生成 main() 函数体 ===
    generate_main_body_inner(&root_assignments, &matched_styles, &handlers, &css_rules, opts, &shared_state)
}

/// 编译 HTML+CSS+JS 为完整可编译的 main.rs（使用默认选项）
pub fn compile(html_path: &str, css_path: &str, js_path: &str) -> String {
    compile_with_options(html_path, css_path, js_path, &CompileOptions::default())
}

/// 编译 HTML+CSS+JS 为完整可编译的 main.rs（可配置窗口参数）
pub fn compile_with_options(html_path: &str, css_path: &str, js_path: &str, opts: &CompileOptions) -> String {
    let body = compile_body_with_options(html_path, css_path, js_path, opts);
    let mut output = String::new();
    output.push_str("//! Generated by toolchain compiler\n\n");
    output.push_str("use renderer::WebWindow;\n\n");
    output.push_str("fn main() {\n");
    output.push_str(&body);
    output.push_str("}\n");
    output
}

/// 为 HTML 元素树分配变量名（递归，含子元素）
///
/// 命名规则：
/// - 有 id 的用 id（`id="inc-btn"` → `inc_btn`）
/// - 有 class 的用第一个 class
/// - 否则用 tag 名（重复则加数字后缀）
fn assign_variable_names(elements: &[HtmlElement]) -> Vec<VarAssignment> {
    let mut result = Vec::new();
    let mut tag_counts: HashMap<String, usize> = HashMap::new();
    collect_recursive(elements, &mut tag_counts, &mut result);
    result
}

/// 仅为顶层元素分配变量名（非递归，用于代码生成）
pub(crate) fn assign_root_variable_names(elements: &[HtmlElement]) -> Vec<VarAssignment> {
    let mut result = Vec::new();
    let mut tag_counts: HashMap<String, usize> = HashMap::new();
    for el in elements {
        let name = generate_var_name(el, &mut tag_counts);
        result.push(VarAssignment {
            name: name.clone(),
            element: el.clone(),
        });
    }
    result
}

/// 构建完整元素列表（含子元素）用于 CSS/JS 匹配
pub(crate) fn build_all_element_vars(elements: &[HtmlElement]) -> Vec<(String, HtmlElement)> {
    let all = assign_variable_names(elements);
    all.into_iter().map(|a| (a.name, a.element)).collect()
}

/// 递归收集所有元素（含子元素）并分配变量名
fn collect_recursive(
    elements: &[HtmlElement],
    tag_counts: &mut HashMap<String, usize>,
    result: &mut Vec<VarAssignment>,
) {
    for el in elements {
        let name = generate_var_name(el, tag_counts);
        result.push(VarAssignment {
            name: name.clone(),
            element: el.clone(),
        });
        collect_recursive(&el.children, tag_counts, result);
    }
}

/// 为单个元素生成变量名
fn generate_var_name(el: &HtmlElement, tag_counts: &mut HashMap<String, usize>) -> String {
    // 优先用 id
    if let Some(id) = el.attributes.get("id") {
        // 将 id 中的连字符转为下划线
        let name = id.replace('-', "_");
        return name;
    }

    // 其次用 class
    if let Some(class) = el.attributes.get("class") {
        if let Some(first_class) = class.split_whitespace().next() {
            let name = first_class.replace('-', "_");
            return name;
        }
    }

    // 否则用 tag 名
    let count = tag_counts.entry(el.tag.clone()).or_insert(0);
    *count += 1;
    if *count == 1 {
        el.tag.clone()
    } else {
        format!("{}_{}", el.tag, count)
    }
}

/// 为元素树生成 DOM 构建代码（递归）
pub(crate) fn generate_element_code_inner(
    el: &HtmlElement,
    var_name: &str,
    depth: usize,
    tag_counts: &mut HashMap<String, usize>,
) -> String {
    let indent = "    ".repeat(depth);
    let mut code = String::new();

    code.push_str(&format!("{}let {} = doc.borrow().create_element(\"{}\");\n", indent, var_name, el.tag));

    // 设置所有属性
    for (key, value) in &el.attributes {
        code.push_str(&format!("{}{}.borrow_mut().set_attribute(\"{}\", \"{}\");\n",
            indent, var_name, key, value.replace('\\', "\\\\").replace('"', "\\\"")));
    }

    // 设置文本内容
    if !el.text_content.is_empty() {
        let escaped = el.text_content.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("{}{}.borrow_mut().set_text_content(\"{}\");\n",
            indent, var_name, escaped));
    }

    // 递归子元素
    for child in &el.children {
        let child_name = generate_var_name(child, tag_counts);
        code.push_str(&generate_element_code_inner(child, &child_name, depth + 1, tag_counts));
        code.push_str(&format!("{}{}.borrow_mut().append_child({}.clone());\n",
            indent, var_name, child_name));
    }

    code
}

/// 生成 main() 函数体（供 include! 使用）
pub(crate) fn generate_main_body_inner(
    assignments: &[VarAssignment],
    matched_styles: &[(String, String)],
    handlers: &[js::EventHandler],
    css_rules: &[css::CssRule],
    opts: &CompileOptions,
    shared_state: &[js::SharedStateVar],
) -> String {
    let mut code = String::new();

    // === 创建窗口 ===
    code.push_str(&format!(
        "    let mut window = WebWindow::new(\"{}\", {}, {});\n",
        opts.title.replace('\\', "\\\\").replace('"', "\\\""),
        opts.width,
        opts.height,
    ));
    code.push_str("    let doc = window.document();\n\n");

    // === 生成元素构建代码 ===
    code.push_str("    // ====== Compiled from index.html ======\n\n");

    let mut var_names: Vec<(String, String)> = Vec::new(); // (var_name, element_id_or_class)
    let mut tag_counts: HashMap<String, usize> = HashMap::new();

    for assignment in assignments {
        let el_code = generate_element_code_inner(&assignment.element, &assignment.name, 1, &mut tag_counts);
        code.push_str(&el_code);
        code.push('\n');

        // 收集变量名用于挂载到 body
        var_names.push((assignment.name.clone(), assignment.element.attributes.get("id").cloned().unwrap_or_default()));
    }

    // === 挂载到 body ===
    code.push_str("    // ====== Mount to body ======\n\n");
    for (var_name, _) in &var_names {
        code.push_str(&format!("    doc.borrow().body().borrow_mut().append_child({}.clone());\n", var_name));
    }
    code.push('\n');

    // === 应用样式 ===
    code.push_str("    // ====== Compiled from style.css ======\n\n");
    for (var_name, style_str) in matched_styles {
        let escaped = style_str.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("    {}.borrow_mut().set_style(\"{}\");\n", var_name, escaped));
    }

    // 应用 body 样式（body 由 Document::new() 原生创建，不经过 HTML 解析）
    for rule in css_rules {
        if rule.selector.trim() == "body" && !rule.declarations.is_empty() {
            let style_str = rule.declarations.iter()
                .map(|(k, v)| format!("{}: {}", k, v))
                .collect::<Vec<_>>()
                .join("; ");
            let escaped = style_str.replace('\\', "\\\\").replace('"', "\\\"");
            code.push_str(&format!("    doc.borrow().body().borrow_mut().set_style(\"{}\");\n", escaped));
        }
    }
    code.push('\n');

    // === 生成共享状态变量 ===
    if !shared_state.is_empty() {
        code.push_str("    // 共享状态（JS 全局变量）\n");
        for sv in shared_state {
            code.push_str(&format!(
                "    let {} = std::rc::Rc::new(std::cell::RefCell::new({}i32));\n",
                sv.name, sv.initial_value
            ));
        }
        code.push('\n');
    }

    // === 生成事件处理器 ===
    code.push_str("    // ====== Compiled from app.js ======\n\n");

    for handler in handlers {
        // 生成 clone 变量（DOM 元素）
        for cv in &handler.cloned_vars {
            let base = cv.trim_end_matches("_clone");
            code.push_str(&format!("    let {} = {}.clone();\n", cv, base));
        }

        // 生成 clone 变量（共享状态 Rc）
        for sv_name in &handler.shared_vars {
            code.push_str(&format!("    let {}_clone = {}.clone();\n", sv_name, sv_name));
        }

        // 生成 add_event_listener 调用
        code.push_str(&format!(
            "    {}.borrow_mut().add_event_listener(\"{}\", Box::new(move |_: &dom::Event| {{\n",
            handler.element_var, handler.event_type
        ));

        // 处理器体
        for line in handler.body_code.lines() {
            code.push_str(&format!("        {}\n", line));
        }

        code.push_str("    }));\n\n");
    }

    // === 启动 ===
    code.push_str("    // ====== Start rendering ======\n\n");
    code.push_str("    window.run();\n");

    code
}

/// 编译为完整 main.rs 并写入输出文件
pub fn compile_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}

/// 编译为 main() 函数体并写入输出文件（用于 include! 方式）
pub fn compile_body_to_file(html_path: &str, css_path: &str, js_path: &str, output_path: &str) {
    let code = compile_body(html_path, css_path, js_path);
    if let Some(parent) = std::path::Path::new(output_path).parent() {
        fs::create_dir_all(parent).ok();
    }
    fs::write(output_path, &code)
        .unwrap_or_else(|e| panic!("Cannot write output '{}': {}", output_path, e));
}

#[cfg(test)]
#[path = "lib.test.rs"]
mod tests;
