//! codegen 模块测试

use super::*;
use crate::html::HtmlElement;
use crate::js::EventHandler;
use crate::VarAssignment;

fn make_element(tag: &str) -> HtmlElement {
    HtmlElement {
        tag: tag.into(),
        attributes: std::collections::HashMap::new(),
        text_content: String::new(),
        children: vec![],
    }
}

#[test]
fn test_generate_full_source_empty() {
    let source = generate_full_source(&[], &[], &[]);
    assert!(source.contains("Generated by rust-test compiler"));
    assert!(source.contains("use render_wgpu::WebWindow;"));
    assert!(source.contains("fn main() {"));
    assert!(source.ends_with("}\n"));
}

#[test]
fn test_codegen_generate_main_body_has_window() {
    let body = CodeGenerator::generate_main_body(&[], &[], &[]);
    assert!(body.contains("WebWindow::new"));
    assert!(body.contains("window.run()"));
}

#[test]
fn test_generate_element_code_basic() {
    let el = make_element("div");
    let mut counts = std::collections::HashMap::new();
    let code = generate_element_code(&el, "my_div", 0, &mut counts);
    assert!(code.contains("create_element(\"div\")"));
    assert!(code.contains("my_div"));
}

#[test]
fn test_generate_element_code_with_text() {
    let mut el = make_element("span");
    el.text_content = "hello world".into();
    let mut counts = std::collections::HashMap::new();
    let code = generate_element_code(&el, "sp", 0, &mut counts);
    assert!(code.contains("set_text_content(\"hello world\")"));
}

#[test]
fn test_generate_element_code_with_attributes() {
    let mut el = make_element("input");
    el.attributes.insert("type".into(), "text".into());
    el.attributes.insert("placeholder".into(), "Enter...".into());
    let mut counts = std::collections::HashMap::new();
    let code = generate_element_code(&el, "inp", 0, &mut counts);
    assert!(code.contains("set_attribute(\"type\", \"text\")"));
    assert!(code.contains("set_attribute(\"placeholder\", \"Enter...\")"));
}

#[test]
fn test_generate_element_code_with_children() {
    let child = make_element("span");
    let parent = HtmlElement {
        tag: "div".into(),
        attributes: std::collections::HashMap::new(),
        text_content: String::new(),
        children: vec![child],
    };
    let mut counts = std::collections::HashMap::new();
    let code = generate_element_code(&parent, "parent", 0, &mut counts);
    assert!(code.contains("create_element(\"div\")"));
    assert!(code.contains("create_element(\"span\")"));
    assert!(code.contains("append_child"));
}

#[test]
fn test_generate_element_code_depth_indentation() {
    let el = make_element("p");
    let mut counts = std::collections::HashMap::new();
    let code = generate_element_code(&el, "p1", 2, &mut counts);
    // depth 2 means 8 spaces of indentation
    assert!(code.contains("        "));
}

#[test]
fn test_generate_full_source_with_element() {
    let el = make_element("button");
    let assignment = VarAssignment { name: "btn".into(), element: el };
    let source = generate_full_source(&[assignment], &[], &[]);
    assert!(source.contains("create_element(\"button\")"));
    assert!(source.contains("append_child(btn.clone())"));
}
